name: artifact

on: [push]

env:
 ARTIFCAT_NAME: myartifact

 jobs:
   main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      use: actions/checkout@v2
    - name: upload the artifactory
      use: actions/upload-artifactory@v2
      with:
       name: ${{env.ARTIFACTORY_NAME}}
       path: .
 
 
 
 
